### PR TITLE
St/base url normalization

### LINKED ISSUE #1861: Installing Flarum from /index.php causes wrong base url
## Bug Report

**Current Behavior**
Installing Flarum from `/index.php` works but causes an invalid url to be used in `config.php`, thus preventing access to the forum after install.

**Steps to Reproduce**
1. Install Flarum according to https://flarum.org/docs/install.html
2. At the step "navigate to your forum in a web browser", append `/index.php` at the end
3. Follow the web installation
4. When install is finished, you are redirected to `/index.php` which shows "Something went wrong while trying to load the full version of this site. Try hard-refreshing this page to fix the error" Accessing `/` shows the same error
5. Assets are loaded from `/index.php/assets/forum-575aab17.css` which causes 404 errors 
6. You can observe  `/index.php` being used in `config.php`

**Expected Behavior**
The installation page should either not be available at `/index.php`, or remove `index.php` from the install url automatically.

**Screenshots**
Probably not needed, let me know otherwise.

**Environment**
- Flarum version: beta 9, and probably dev-master
- Webserver: apache, but probably others
- Hosting environment: tried locally

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

It's a blank install.

When enabling debug mode, the assets show the following 500 error:

```
Flarum\Http\Exception\RouteNotFoundException: /assets/forum-575aab17.css in file /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php on line 60
Stack trace:
  1. Flarum\Http\Exception\RouteNotFoundException-&gt;() /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php:60
  2. Flarum\Http\Middleware\DispatchRoute-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
  3. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php:58
  4. Flarum\Http\Middleware\ShareErrorsFromSession-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
  5. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Middleware/SetLocale.php:51
  6. Flarum\Http\Middleware\SetLocale-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
  7. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php:25
  8. Flarum\Http\Middleware\CheckCsrfToken-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
  9. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php:34
 10. Flarum\Http\Middleware\AuthenticateWithSession-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
 11. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php:52
 12. Flarum\Http\Middleware\RememberFromCookie-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
 13. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Middleware/StartSession.php:62
 14. Flarum\Http\Middleware\StartSession-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
 15. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php:48
 16. Flarum\Http\Middleware\CollectGarbage-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
 17. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php:29
 18. Flarum\Http\Middleware\ParseJsonBody-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
 19. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Middleware/HandleErrorsWithWhoops.php:43
 20. Flarum\Http\Middleware\HandleErrorsWithWhoops-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
 21. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php:83
 22. Zend\Stratigility\MiddlewarePipe-&gt;process() /home/clark/Projects/flarum-install/vendor/middlewares/request-handler/src/RequestHandler.php:84
 23. Middlewares\RequestHandler-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
 24. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/middlewares/base-path-router/src/BasePathRouter.php:97
 25. Middlewares\BasePathRouter-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
 26. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Middleware/OriginalMessages.php:41
 27. Zend\Stratigility\Middleware\OriginalMessages-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
 28. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/middlewares/base-path/src/BasePath.php:53
 29. Middlewares\BasePath-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/Next.php:60
 30. Zend\Stratigility\Next-&gt;handle() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php:83
 31. Zend\Stratigility\MiddlewarePipe-&gt;process() /home/clark/Projects/flarum-install/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php:72
 32. Zend\Stratigility\MiddlewarePipe-&gt;handle() /home/clark/Projects/flarum-install/vendor/zendframework/zend-httphandlerrunner/src/RequestHandlerRunner.php:95
 33. Zend\HttpHandlerRunner\RequestHandlerRunner-&gt;run() /home/clark/Projects/flarum-install/vendor/flarum/core/src/Http/Server.php:46
 34. Flarum\Http\Server-&gt;listen() /home/clark/Projects/flarum-install/public/index.php:22
```

**Possible Solution**
Same as expected behavior.

**Additional Context**
Multiple people seem to have hit issues that could be related to this. Most recently https://discuss.flarum.org/d/21143-fatal-error-please-help but I'm not 100% sure this is the same issue. Other people had managed to get an `index.php` in their `config.php` and this is probably one way to inadvertently do it.

### PR DESCRIPTION
**Pull request by relax4o**
**Fixes #1861**

**Changes proposed in this pull request:**
The PR contains a couple of more fixes which were related to the referenced issue.
The Web and CLI installers are a bit more safe to use avoiding unexpected further issues like an incorrect `mail_from` due to unfulfilled base url via CLI.

**Reviewers should focus on:**
Are you happy with the way I dealt with the issue?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `php vendor/bin/phpunit`).

Note:
This is my first contribution to an open source project ever. I tried to follow the other's ways of doing things. If I did something wrong I'll be more than happy to point it to me so I can get into this faster.

### CODE REVIEW

**Comment by franzliedke** [comment]
Hey, thank you for that awesome first contribution, we really appreciate it! :heart: 

And it must say, this looks amazing for a first PR, so well done. :+1: 

That said, please give us a bit of time to look into this. We're pretty busy finalizing the upcoming release (due on Friday) right now.

Until then, you could take care of the low-hanging fruit which was reported by StyleCI: https://github.styleci.io/analyses/zeOMDr

**Comment by franzliedke** [comment]
Damn, you're fast. :wink:

**Comment by relax4o** [comment]
I am a little bit familiar with the process so I waited for the automated report. :D 

I need to setup my PhpStorm according to the StyleCI so the auto-format won't cause any more troubles.

**Comment by relax4o** [comment]
Awesome. Thanks for the feedback.

This will be the first thing to do tomorrow.

**Comment by relax4o** [comment]
I hope I got the right idea of the value objects and did it correctly.

Although, this approach is very open to different implementations and not sure about correctness/incorrectness.

**Comment by franzliedke** [comment]
@relax4o Thanks a lot for your awesome PR!

I can't believe this is your first open-source contribution - you did really well. Thanks for trying to respect our conventions and sticking to what's there.

I pushed a little bit of cleanup in 3417c0cbee8d1d6097214b29019f795fea6042c6 - I sometimes find this easier than doing lots of review iterations. Apart from small things that are just a matter of taste, I mostly removed docblocks that don't add any information where we have typehints (in fact, they had already gotten out of sync with the implementation), and extracted one more method.

That's what I like about value objects: they tend to attract logic, which is great for encapsulation and - in this case - reuse.

Thanks again! :heart:

**Comment by STotev** [comment]
Thanks for accepting my PR.

I saw you've changed all my UK style into American style. I'll try to stick with American next time. :D 

Great additions. Thank you for doing it for me.

By the way, it's me relax4o. This has become my official account so I moved everything here. Further comments and PRs will be added from this account.

**Pull request merged**
