### PR TITLE
chore: maintenance pre-1.2 release

### PR DESCRIPTION
**Pull request by davwheat**
**Changes proposed in this pull request:**

Performs minor repo maintenance in the lead up to the v1.2 release.

- Bumps JS dependencies
- Bumps Yarn version

**Reviewers should focus on:**

Missing anything?

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [x] Core developer confirmed locally this works as intended.
- [x] Tests have been added, or are not appropriate here.

### CODE REVIEW

**Comment by davwheat** [comment]
Note: failing task is `extend.ts` which gets fixed as part of #3214

**Review by SychO9 — APPROVED** [review]

**Review by askvortsov1 — APPROVED** [review]
LGTM, assuming rebasing once #3214 is fixed makes CI pass

**Comment by datitisev** [comment]
Do we want to perhaps add to this PR or another one a line to `.gitattributes` to hide yarn lock diff by default? Like `package-lock.json`?

**Comment by davwheat** [comment]
Yeah that's a good idea

**Pull request merged**
