### PR TITLE
Hide diff for compiled diff files

### LINKED ISSUE #1048: Hide diff for compiled js files
suggested in https://github.com/flarum/core/issues/1024#issuecomment-251503338

as `js/*/dist/app.js` are auto generated files and also Babel add a lot's of ugly stuff this can help reading commits.

### PR DESCRIPTION
**Pull request by janga1997**
Fixes #1048 
@franzliedke

### CODE REVIEW

**Comment by franzliedke** [comment]
Great, thank you!

We're also interested in having this in our extensions' repositories, if anybody wants to do that. ;)

**Comment by janga1997** [comment]
@franzliedke there seem to be about 20 extensions' repositories.
I suppose you want to do the same in each one of them?

**Comment by Luceos** [comment]
@janga1997 thanks for this, I'm adding it to the Flagrow extensions 👍

**Comment by franzliedke** [comment]
> I suppose you want to do the same in each one of them?

@janga1997 Yes, that's what I meant.

**Comment by janga1997** [comment]
@franzliedke Maybe a silly question. But can I open a single pull request for all the sub repositories in for flarum? Or is opening 20 PRs the only way?

**Comment by franzliedke** [comment]
20 PRs is the only option, I'm afraid. Maybe you can split the work with someone on our Gitter chat?

**Comment by janga1997** [comment]
@franzliedke Nah. I want to do it, just thought maybe there was a quicker way.

**Comment by dav-is** [comment]
Should be extremely simple with the GitHub web interphase.

**Comment by janga1997** [comment]
It is. But I believe I still have to fork 20 repos and commit a single line in each one of them?

**Comment by janga1997** [comment]
@dav-is Never mind. It is quite easy.

**Comment by janga1997** [comment]
@dav-is Never mind. It is quite easy.

**Comment by Luceos** [comment]
If you click edit on the file on Github, it will create a fork and PR automatically on behalf of you.

Kicks ass!

**Comment by janga1997** [comment]
That's exactly what I did. I've already made the PRS

**Comment by janga1997** [comment]
Do merge if anybody's free.

**Comment by franzliedke** [comment]
Thanks for all of these!

**Pull request merged**
