### PR TITLE
#679 Ask for confirmation before "Mark all as Read"

### PR DESCRIPTION
**Pull request by bogdanteodoru**
https://github.com/flarum/flarum-ext-english/pull/59 should me merged as well.

### CODE REVIEW

**Comment by franzliedke** [comment]
Thank you very much!

**Comment by tobscure** [comment]
Oops, this isn't quite right!

1) The confirmation has incorrectly been implemented on the DiscussionListItem component when clicking the number of unread comments... The issue is actually about a confirmation on the "Mark All as Read" button in the [top-right corner of the IndexPage](https://github.com/flarum/core/blob/master/js/forum/src/components/IndexPage.js#L361).

2) The translation in flarum-ext-english#59 reads "Are you sure you want to mark all **notifications** as read?" which is incorrect.

**Comment by franzliedke** [comment]
Sorry about this. :(

**Comment by bogdanteodoru** [comment]
Sorry for this @tobscure. I will update the code and language file.

**Comment by bogdanteodoru** [comment]
How should the text sound? 

"Are you sure you want to mark all threads/posts as read?"

**Comment by franzliedke** [comment]
"all discussions", I'd say

**Comment by bogdanteodoru** [comment]
Lets wait for @tobscure's opinion on this to make it right from the start :)

**Comment by tobscure** [comment]
"Are you sure you want to mark all discussions as read?"

**Comment by tobscure** [comment]
"Are you sure you want to mark all discussions as read?"

**Pull request merged**
