### PR TITLE
Required before releasing beta 9

### PR DESCRIPTION
**Pull request by datitisev**
Required before releasing beta 9.

### CODE REVIEW

**Comment by datitisev** [comment]
I have no idea what StyleCI is complaining about. 🙆‍♂

**Comment by franzliedke** [comment]
Please, always rebase your branch on top of master instead of merging master. :heart: 

In this case, we can just squash-merge the PR when we do the release, so it won't matter much, but for the future... Especially long-running PRs get a messy history with too much merging.

**Comment by datitisev** [comment]
@franzliedke I apologize, I thought I did locally (as some weird merge magic went on), but it seems I didn't, and GitHub wanted me to update it.

**Comment by franzliedke** [comment]
:tada:

**Pull request merged**
