### PR TITLE
Change remember in LogInModal to switch to fit style

### PR DESCRIPTION
**Pull request by issyrocks12**
A checkbox doesn't fit the style of Flarum's clean look. This changes it to a switch to fit the style of Flarum.

### CODE REVIEW

**Comment by franzliedke** [comment]
@issyrocks12 Looks like something went wrong with the diff of the compiled files there.

Please delete your `node_modules` folder in js/forum and run `npm install && gulp` again.

**Comment by issyrocks12** [comment]
There we go, sorry about that, it was a bower issue.

**Comment by franzliedke** [comment]
Hmm, that still wasn't *quite* right. I fixed that, squashed everything and [pushed this directly to master](https://github.com/flarum/core/commit/bb1c655c90dac4b1f4fd2ddff6a5c310306912d5).

Thank you!

**Comment by franzliedke** [comment]
Hmm, looks like this is no longer usable by keyboard (i.e. tab to the switch and toggle it with spacebar).

@issyrocks12 Would you be willing to submit an additional PR?

**Pull request closed without merging**
