### PR TITLE
Add DB prefix to PHP tests

### PR DESCRIPTION
**Pull request by datitisev**
Only for PHP 7.3 & MySQL 5.7.

Also simplified job names to show it has a custom prefix.

Only way this worked was by excluding every other job :/

### CODE REVIEW

**Comment by luceos** [comment]
Might want to run prefix mode on mariadb too, that would remove one entry in the exclude, right?

**Comment by datitisev** [comment]
@luceos Yep. Didn't do so as Travis only had the prefix with MySQL. If wanted, I can try to add PHP 7.4 snapshot tests to this PR.

**Comment by luceos** [comment]
Yeah but 7.4 is allowed to fail; not sure you can set that?

**Comment by datitisev** [comment]
@luceos Not necessary allowed to fail, but we can make it exit with a success status code even if it does fail.

**Comment by datitisev** [comment]
Added PHP 7.4, it will always show as success in the status check, but you can see the log when clicking details.

**Comment by matteocontrini** [comment]
Hi everyone, I wanted to mention that GitHub Actions can be run inside Docker containers as well, so using an image with PHP 7.4 preinstalled would be a way to avoid installing it every time.

**Comment by datitisev** [comment]
@matteocontrini Thanks for the info, though I don't think it really matters that much as our tests fail on PHP 7.4 anyway, so it's just there to remind us \:).

**Comment by luceos** [comment]
A test that succeeds on 7.4 even when they fail without direct feedback doesn't make a lot of sense. If looking at the logs are the only way to check actual compliance with the new version, I'd rather not have this version right now. Feel free to push this back to the github actions team, allowed to fail with clear visual feedback is a must-have.

**Comment by franzliedke** [comment]
Agreed, let's avoid 7.3 for now then.

@datitisev Shouldn't it be possible to model this only with "include" and no "exclude"? :thinking:

**Comment by datitisev** [comment]
@franzliedke I tried it, but `include` only seems to be for including extra information??? Not sure, I just got weird errors that didn't offer any insight into what the problem was. Something about `G15` or `G16` (?).

Ok, I'll remove PHP 7.4.

**Pull request merged**
