### PR TITLE
missing meta description from admin area

### LINKED ISSUE #489: Setting forum description doesn't show in html
When setting the forum description it saves, but the html doesn't reflect it post multiple full refreshes.

### PR DESCRIPTION
**Pull request by Luceos**
fixes #489

### CODE REVIEW

**Comment by franzliedke** [comment]
Thanks!

**Comment by tobscure** [comment]
:+1:

**Comment by yerbol89** [comment]
@Luceos in this you fix code duplicate home page meta description. Description show home page and in post page. Its bad.

Please in post show page add for description in 160 symbols in post text.

**Comment by Luceos** [comment]
@yerbol89 please open a new issue. Your problem is completely unrelated to what I fixed. Because the only thing i fixed is sending the description to the frontend views. Your issue is about whát is seen as the description, that is probably discussable. 

Posting in this pull request your comments will get lost anyway.

**Pull request merged**
