### PR TITLE
Correct redirect uri in OAuth2 Controller

### PR DESCRIPTION
**Pull request by sijad**

### CODE REVIEW

**Comment by franzliedke** [comment]
As detailed in the issue, the `getOriginalRequest()` method is not part of the `ServerRequestInterface` interface.

**Comment by sijad** [comment]
@franzliedke it's just an interface, it implemented [here](https://github.com/zendframework/zend-stratigility/blob/master/src/Http/Request.php#L71)

**Comment by franzliedke** [comment]
No, it's not "just" an interface. We typehint it so that Flarum can be used with other PSR-7 compatible middleware layers.

**Comment by sijad** [comment]
@franzliedke sorry about that, how about now?

**Comment by franzliedke** [comment]
Looking good. I'll probably create a helper for this.

**Comment by sijad** [comment]
thanks for reviewing my code, flarum/flarum-ext-auth-twitter#3 need to be updated too, please let me know what should I do

**Comment by franzliedke** [comment]
Please do the same there.

**Pull request merged**
