### PR TITLE
Prevent deletion of default/all locale(s)

### LINKED ISSUE #623: Check whether langpack is the default language before disabling
At present it is possible to disable a language pack that the admin has selected as the forum's default language. This can result in the translator attempting to fall back to resources that are no longer valid.

Flarum needs to do the following whenever an admin disables an extension:
1. Check whether the extension is a language pack.
2. If yes: check whether that language pack has been selected as the forum's default language.
3. If yes: fail to disable the extension and warn the user to change the default language first.

Or it could present the user with a list of installed language packs _other than the one the user is trying to disable_, allowing the user to selected a new default language right there ... upon which the extension can be disabled.

### PR DESCRIPTION
**Pull request by dav-is**
Fix #623

### CODE REVIEW

**Comment by Luceos** [comment]
Really love this PR, well done @dav-is

**Comment by dav-is** [comment]
@luceos Wasn't sure what the message should be. Suggestions? Should it be a translated string? Am I writing exceptions correctly?

**Comment by Luceos** [comment]
Yes it's fine. But you're preventing disabling an extension that is the configured _default_ locale, not _all_ locales.

**Comment by Luceos** [comment]
thanks, just disregard styleci, it should be set to run automatically instead of bothering us

**Comment by franzliedke** [comment]
Nice job, thank you! ❤️ 

And I again forgot to squash. :man_facepalming:

**Comment by franzliedke** [comment]
@dav-is Two amendments...

- a bugfix: https://github.com/flarum/core/commit/9349ed13fc74f041ca93e2d057b2c3ac3629a1d8
- and HTTP semantics: https://github.com/flarum/core/commit/d3753d94ae5c26567c820abb02f4f96d944311dd

**Comment by franzliedke** [comment]
@dav-is FYI, there was another bug. Fixed this in the `next-back` branch: https://github.com/flarum/core/commit/6f7231da034d04e954d00442261abf4435583342

**Pull request merged**
