### PR TITLE
added integration with codecov to track coverage of tests

### PR DESCRIPTION
**Pull request by Luceos**
Would like to propose tracking code coverage. We can do this automatically by using codecov.io (just use your account to set it up @flarum/core ). The entry below sends the stats over to codecov.

### CODE REVIEW

**Comment by franzliedke** [comment]
Not sure we want that at this point. Can be slightly depressing... also I'm in the camp of those who doubt the usefulness of code coverage as metric. It can lead to the wrong goals in testing.

**Comment by Luceos** [comment]
@franzliedke we don't need to publish this and let's face the fact at some point we need to know how far the tests are covering code. Maybe you (core devs) don't need it, but those that write the code do ;) It makes their lives much easier.

**Comment by franzliedke** [comment]
That's convincing. :+1:

**Comment by Luceos** [comment]
I meant "those that write the tests do", updated comment ;)

Ps it's also a goal to work towards.

**Comment by franzliedke** [comment]
@tobscure Do you agree?

**Pull request merged**
