### PR TITLE
Replace $app->url() with url-generated link to index

### PR DESCRIPTION
**Pull request by askvortsov1**
The `url` method of Container was removed in #2142.  Works locally.

### CODE REVIEW

**Review by tankerkiller125 — APPROVED** [review]

**Review by clarkwinkelmann — CHANGES_REQUESTED** [review]
I think everywhere else we make a link to the homepage we use `->to('forum')->base()` https://github.com/flarum/core/blob/df8f73bd3d656e073dcfff5bddd8e7692ca19162/src/Api/Serializer/ForumSerializer.php#L67

Or an alternative could be to use the `default` named route https://github.com/flarum/core/blob/2431df5602e218d77388cec0019d13a473912be0/src/Forum/ForumServiceProvider.php#L207

Using `index` would create a link to `/all` when a different homepage has been selected I believe.

**Comment by askvortsov1** [comment]
Good catch, thanks!

**Review by clarkwinkelmann — APPROVED** [review]

**Comment by franzliedke** [comment]
Removed this from the milestone as this is just a regression from another change and not relevant for the changelog or anything like that, IMO. I hope you don't mind.

**Comment by askvortsov1** [comment]
Thanks! I only added it so that we don't forget to fix it before release. The milestone will need a comb-over before release anyways

**Pull request merged**
