### PR TITLE
TypeScript infrastructure

### PR DESCRIPTION
**Pull request by datitisev**
Will probably want to include some shims
<details>
<summary>Old example shims in WIP rewrite branch</summary>

https://github.com/flarum/core/blob/4c8af1cdf876b9bd3770f76c33eb6c9ac80608f0/js/webpack-flarum-shims.d.ts#L7-L17

https://github.com/flarum/core/blob/4c8af1cdf876b9bd3770f76c33eb6c9ac80608f0/js/shims.d.ts#L3-L7
</details>

---

- Webpack config is temporarily in this PR to avoid weird NPM garbage & publishing buggy flarum-webpack-config release
  - See https://github.com/flarum/flarum-webpack-config/pull/3

### CODE REVIEW

**Comment by askvortsov1** [comment]
@datitisev perhaps we should have this PR be just the setup of Typescript infrastructure, and follow up with the actual typescript changes in a second PR? And merge the first one in now?

**Comment by datitisev** [comment]
@askvortsov1 Ok, will do.

**Comment by franzliedke** [comment]
Thanks, looks good! Can we undraft this to get it merged?

Just one question: what's the purpose of `@babel/plugin-syntax-dynamic-import`?
Okay, I kinda understand that from its description on NPM, but how is it related to TypeScript?

**Comment by datitisev** [comment]
I... don't know what that does. I copied it over from my Mithril branch. Looking at the babel docs for that package did not help in understanding. I think it has something to do with `import()` functions (not import statements) returning Promises..?

**Comment by franzliedke** [comment]
Yeah, those allow you to import scripts at runtime, I don't think that's needed for TypeScript at all. Please remove that, then we can merge. :hugs:

**Pull request merged**
