### PR TITLE
Core key reorganization

### PR DESCRIPTION
**Pull request by dcsjapan**
Improved consistency for existing core translation key names

See flarum/core#265

- “Go to” buttons need to be changed to dismiss buttons in three files:
 - ChangeEmailModal.js
 - ForgotPasswordModal.js
 - SignUpModal.js
- Keys for these buttons have been changed; only the code needs to be fixed.
- Requires compiler to resolve key name references

### CODE REVIEW

**Comment by franzliedke** [comment]
The code changes look good. :+1:

**Comment by dcsjapan** [comment]
Thanks! :)

**Comment by tobscure** [comment]
Merged! :tada: Thanks for your work, @dcsjapan!

**Comment by dcsjapan** [comment]
Glad to help! Once I've got through the documentation I'll start working on the hardcoded strings.

If I may be allowed another GitHub noobie question:

Now that it's merged, can I just delete that branch on my end and update from your master?

**Pull request merged**
