### PR TITLE
Fix syntax errors when compiling js files

### LINKED ISSUE #1047: Only one default export allowed per module Syntax Error
when I run `./scripts/compile.sh` in terminal I get this errors:

```
SyntaxError in plugin 'gulp-babel'
Message:
    flarum/vendor/flarum/core/js/lib/models/Discussion.js: Only one default export allowed per module. (106:0)
```

and

```
SyntaxError in plugin 'gulp-babel'
Message:
    flarum/vendor/flarum/core/js/lib/models/Discussion.js: Only one default export allowed per module. (106:0)
```
## Bug report
- Version of Flarum: master brach
- PHP version: 5.6.26
- Hosted environment: local
## Log files

```
[13:15:00] Using gulpfile flarum/vendor/flarum/core/js/forum/gulpfile.js
[13:15:00] Starting 'default'...
SyntaxError in plugin 'gulp-babel'
Message:
    flarum/vendor/flarum/core/js/lib/models/Discussion.js: Only one default export allowed per module. (106:0)
[13:15:07] Finished 'default' after 7.23 s
[13:15:11] Using gulpfile flarum/vendor/flarum/core/js/admin/gulpfile.js
[13:15:11] Starting 'default'...
SyntaxError in plugin 'gulp-babel'
Message:
    flarum/vendor/flarum/core/js/lib/models/Discussion.js: Only one default export allowed per module. (106:0)
[13:15:15] Finished 'default' after 4.05 s
```

### PR DESCRIPTION
**Pull request by sijad**
fixes #1047

### CODE REVIEW

**Comment by tobscure** [comment]
Thanks @sijad :)

**Comment by franzliedke** [comment]
Time for a yarn.lock file maybe?

**Comment by dav-is** [comment]
We could use bithound and eslint as well for PRs and commits?

**Comment by tobscure** [comment]
yes to both

**Pull request merged**
