### PR TITLE
Support extend by callback?

### PR DESCRIPTION
**Pull request by lubobill1990**
**Fixes #0000**
In the document, it seems extend.php can support callback.
**Changes proposed in this pull request:**

**Reviewers should focus on:**

**Screenshot**

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `php vendor/bin/phpunit`).

### CODE REVIEW

**Comment by tobscure** [comment]
Callbacks are already supported (but deprecated) via https://github.com/flarum/core/blob/master/src/Extension/Extension.php#L108

**Comment by lubobill1990** [comment]
Perhaps the code you list here is for extensions installed with composer?

When I add callback to extend in root/extend.php, exception will be thrown and complains that callback::extend() is not exist

**Comment by tobscure** [comment]
Ah I see. The purpose of supporting callbacks is for backwards-compatibility purposes, so we haven't added support for them in the root `extend.php` which is new in beta 8. You can instantiate the `Extend\Compat` extender if you'd like to use a callback in your root `extend.php`.

**Comment by lubobill1990** [comment]
I know, thanks toby.

**Comment by lubobill1990** [comment]
@tobscure I have a question: What's the preferred way to add a event listener to Flarum\Post\Event\Posted in beta 8?

**Comment by tobscure** [comment]
Using a callback ;) We haven't finished implementing extenders for a lot of tasks (including listening for events), there will be issues to track progress soon!

**Comment by lubobill1990** [comment]
Looking forward to it and thanks for your effort!

**Pull request closed without merging**
