### PR TITLE
Throw FileNotFoundException when FileSource path does not exist

### PR DESCRIPTION
**Pull request by datitisev**
**Changes proposed in this pull request:**
- Throw `League\Flysystem\FileNotFoundException` when asset file is not found

**Screenshot**
image

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `php vendor/bin/phpunit`).

### CODE REVIEW

**Comment by tobscure** [comment]
@Franz I was discussing with @datitisev whether we should be depending on `League\Flysystem` for the exception here, rather than just using a `\InvalidArgumentException` or `\RuntimeException`. Thoughts?

**Comment by datitisev** [comment]
@franzliedke What should the message of the exception be?

And why shouldn't we use an existing FileNotFoundException, which provides exactly what the issue is to the user?
Symfony and Illuminate also have FileNotFoundExceptions, if it's just because it's in League then that's not a problem.
I don't really understand why we wouldn't want to use it, sorry.

**Comment by franzliedke** [comment]
I guess it just feels off to use a class from a framework in a file that is otherwise completely free of any framework coupling.

**Comment by franzliedke** [comment]
You can use the exception text from Flysystem's exception. ;)

**Comment by franzliedke** [comment]
Please don't change the dist file.

**Comment by datitisev** [comment]
Oops! Sorry, looks like I accidentally added it when I was testing the exception 🤦‍♂️

**Comment by luceos** [comment]
that branch name 😂 

let's make it a convention 🤣

**Pull request closed without merging**
