### PR TITLE
Add style

### PR DESCRIPTION
**Pull request by fransallen**

### CODE REVIEW

**Comment by Luceos** [comment]
Hi @fransallen I'm not sure where this PR comes from, I see you've translated the title. But at the same time you've removed the error box.

Can you explain the reasoning behind all this?

**Comment by fransallen** [comment]
My mistake, wait, I'll fix it.

**Comment by franzliedke** [comment]
@tobscure Apparently, this adds styling for the "Reset your password" page. Can you review?

**Comment by franzliedke** [comment]
This will probably need to be handled differently (i.e. by adding styles to the existing stylesheet), but maybe some of them can be reused?

**Comment by DogSports** [comment]
I suggest to close this pull request. New design for reset password is already update by this [commit](https://github.com/flarum/core/commit/9392e1bec3fd1fa967e1c59dc23890631aaa997d#diff-21f4cddccb67436f994ec16cb3f72c84)

**Comment by franzliedke** [comment]
Indeed.

**Pull request closed without merging**
