### PR TITLE
Fix issue where posts API doesn't return the right amount of posts

### LINKED ISSUE #2071: Guest users can't load more posts on profiles
## Bug Report

**Current Behavior**
When browsing forums as a guest, the "Load More" button for posts is not shown on user profiles, however if you log in and scroll to the bottom of posts on a profile, the option is shown. 

Occurs on discuss.flarum.org

### PR DESCRIPTION
**Pull request by w-4**
**Fixes #2071**

**Changes proposed in this pull request:**
Check for permissions when getting the post Ids. 

- [x] Tested locally

### CODE REVIEW

**Review by askvortsov1 — APPROVED** [review]
Thank you very much!

**Review by datitisev — APPROVED** [review]
Test locally and it works. Thank you so much! I think I'll want Franz or luceos to take a look before merging, but this LGTM.

**Review by tankerkiller125 — APPROVED** [review]

**Review by Pi-Bouf — APPROVED** [review]

**Review by luceos — APPROVED** [review]

**Comment by luceos** [comment]
We need to identify where we use this method and prevent the whereVisibleTo to be added after that.

**Comment by clarkwinkelmann** [comment]
This sounds like a good fix.

> We need to identify where we use this method

You mean `getPostIds`? That one is private and used only from there.

**Pull request merged**
