### PR TITLE
User online indicators

### PR DESCRIPTION
**Pull request by petermein**
My first contribution to Flarum. I just picked one of the issues good for new contributors.

The issue:
https://github.com/flarum/core/issues/254

I added a helper to display the icon when the condition is met. Added styling from the UserCard.

### CODE REVIEW

**Comment by franzliedke** [comment]
This looks great, thank you very much! I will pull this down to test it tonight.

(The failing StyleCI analysis is not your fault. Toby is working on fixing that...)

**Comment by Luceos** [comment]
Referencing: https://github.com/flarum/core/issues/254

**Comment by tobscure** [comment]
Looks good, thanks!

Nitpicking, but it might be better to consolidate this directly into the PostUser component since it's a unique context and unlikely to be reused anywhere else... i.e.

```js
<div className="PostUser">
  {user.lastSeenTime() && user.isOnline() ? <span className="PostUser-online">{icon('circle')}</span> : ''}
```

**Comment by Luceos** [comment]
@tobscure I'm not sure about that. I would like to be able to use such a state icon seperately from the whole user component, for instance is table listing. Not sure whether you meant that seperation.

One thing I saw: `useronline` should be according to the naming conventions `UserOnline` as a component name in the helpers directory.

**Comment by petermein** [comment]
@Luceos The naming is the same as the username helper class. But indeed maybe it should be userOnline to match the rest of the helper classes. 

Just tell what option you think is best, the helper approach or put the logic inside the component. Il update the PR accordingly.

**Comment by franzliedke** [comment]
Let's go with a small helper, that's what they're there for.

@petermein Please rename to `userOnline` and I'll merge. :)

**Comment by Luceos** [comment]
Changed to camelCasing, let's merge this @flarum/core

**Comment by tobscure** [comment]
:beers:

**Pull request merged**
