### PR TITLE
Fix image avatar alignment in notifications

### LINKED ISSUE #2905: Notification avatar alignment issue
https://discuss.flarum.org/d/27601-flarum-v10-or-above-notification-area-aliment-issues

### PR DESCRIPTION
**Pull request by davwheat**
**Fixes #2905**

**Changes proposed in this pull request:**

Fixes issue introduced with #2822 where image-based avatars would display misaligned in the notifications list.

**Reviewers should focus on:**

Are there any other issues with Notification avatars? Can anyone think of a less hacky way to achieve this?

**Screenshot**

### Before
image

### After
image

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.

### CODE REVIEW

**Review by tankerkiller125 — APPROVED** [review]

**Review by SychO9 — COMMENTED** [review]
Any reason for doing this instead of changing `  align-items: baseline;` to `  align-items: center;` in `.Notification` ?

**Comment by davwheat** [comment]
Doing center will make the avatar centrally aligned on multi-line notifications, which doesn't match the style in previous versions, or the style of the text-based avatars.

**Comment by SychO9** [comment]
> Doing center will make the avatar centrally aligned on multi-line notifications, which doesn't match the style in previous versions, or the style of the text-based avatars.

It doesn't though because of how the notification grid is structured.

**Comment by davwheat** [comment]
If the title is multi-lined, it does.

image

**Comment by SychO9** [comment]
> If the title is multi-lined, it does.
> 
> image

Ah, I see what you mean now, it's because the image itself is a cell of the grid that we can't just change its vertical alignment to middle. Another way of fixing this would be to wrap the notification avatar img with a div or span, then setting the vertical alignment of the `.Avatar` to middle.

**Comment by davwheat** [comment]
I'd agree with something similar to that, but it could break 3rd party styles, annoyingly :(

**Review by SychO9 — APPROVED** [review]
True, we could do that for 2.0, but better avoid for 1.x

**Pull request merged**
