### PR TITLE
Allow override layout template.

### PR DESCRIPTION
**Pull request by liverbool**
| Q               | A
| --------------- | ---
| Bug fix?        | no|
| New feature?    | yes |
| BC breaks?      | no |
| License         | MIT |

Please accept this PR ;)

### CODE REVIEW

**Comment by franzliedke** [comment]
@liverbool Please provide a little more explanation. :)

**Comment by franzliedke** [comment]
@luceos Since you upvoted... can you explain the nuances here? :see_no_evil:

**Comment by luceos** [comment]
@franzliedke instead of using a path for loading the blade, @liverbool correctly uses the namespace defined (eg for [forum](https://github.com/flarum/core/blob/master/src/Forum/ForumServiceProvider.php#L81)). This allows an extension to override the namespace. A path reference cannot be overridden, hence my upvote.

**Comment by franzliedke** [comment]
Turns out this was already taken care of by Toby. :see_no_evil:

**Pull request closed without merging**
