### PR TITLE
Update to Zend Stratigility 1.3

### LINKED ISSUE #1069: Update to Stratigility 1.3
Updating will require some changes in our middleware stack to stay forward-compatible with the upcoming version 2.0 of Stratigility, see https://docs.zendframework.com/zend-stratigility/migration/to-v2/.

Important: MR #1066 should also be reverted as part of this.

### PR DESCRIPTION
**Pull request by franzliedke**
* Fix dependency version constraint. (Reverts #1066.)
* Allow exceptions to be raised when dispatching middleware.
* Fix our error handler middleware (do not implement Stratigility's
  error handler interface, catch exceptions instead).

See https://docs.zendframework.com/zend-stratigility/migration/to-v2/.

Closes #1069.

### CODE REVIEW

**Comment by Luceos** [comment]
@flarum/core  tests fail because Stratigility's minimum php version for 1.3+ is 5.6. We might need to up our version now too.

**Comment by franzliedke** [comment]
Given that 5.6 now only receives security fixes, that probably makes sense anyway.

@tobscure Do you agree?

**Comment by Luceos** [comment]
@franzliedke can you update this PR to update `.travis.yml` and `composer.json` once @tobscure approves?

**Comment by franzliedke** [comment]
That also means, we're now requiring PHP 5.6, but that simply makes sense. :)

**Comment by tobscure** [comment]
Beautiful :)

**Comment by Luceos** [comment]
@franzliedke can you take care of branch deletion if you feel it's now ready as is?

**Comment by franzliedke** [comment]
Done, thanks.

**Pull request merged**
