### PR TITLE
Add descriptions and optimize extensions page (#1379)

### PR DESCRIPTION
**Pull request by ardacebi**
- Adds descriptions to extensions.
- Redesigns the extensions list (includes full titles and descriptions)

**Screenshot**
68747470733a2f2f6672616d617069632e6f72672f39526f46346966546a5531302f66556137584c796e50307658

Fixes change request at #1379 

@franzliedke Is everything OK with this?

### CODE REVIEW

**Comment by TurboProgramming** [comment]
@franzliedke Thanks for the approval, waiting for @tobscure.

**Comment by CDK2020** [comment]
I personally feel instead of this would should have a tooltip with the info. I think a list could get large very fast

**Comment by TurboProgramming** [comment]
@CDK2020 In the future, expanding it to 2 columns can be a fix.

**Comment by TurboProgramming** [comment]
Seeing this after this gets merged will make it more responsive: https://discuss.flarum.org/d/14786-moving-checkboxes-over-to-extension-icons.

**Comment by franzliedke** [comment]
Merging as Toby already approved #1379.

**Pull request merged**
