### PR TITLE
feat: post search adapted with global search

### PR DESCRIPTION
**Pull request by SychO9**
**Part of the 2.0 milestone**

**Changes proposed in this pull request:**
* Adds searching of posts
  * A new search source in the search modal
  * A new page dedicated to post search results (which could technically also be viewed without search when directly going to the link /posts)
  * When a discussion, or user posts, or user liked posts, or user mentioned posts page is currently open, the search modal automatically selects the post search tab and automatically selects the correct filter in context to the current page.

**Screenshot**
image
---
image
image
image
image
image

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

**Comment by luceos** [comment]
Why is the implementation of author different than the other related to users? I feel like their use should be identical or at least similar in such a way that instead of relying on users to know IDs, we use usernames.

**Comment by SychO9** [comment]
That's how the filter was implemented prior to this. I think these user filters should all support username and ID, and in the UI default to use the username, in the future we will likely add something to allow hiding usernames which is why ID still matters.

will modify them as such.

**Comment by SychO9** [comment]
updated

image
image

**Comment by luceos** [comment]
If this works, I'd say start merging everything in whenever it suits you and we'll start testing end-to-end when you give the sign.

💪 Excellent work, also from @iamdarkle. Really looks awesome.

**Pull request merged**
