### PR TITLE
Add descriptions and optimise extensions page

### PR DESCRIPTION
**Pull request by DogSports**
Add descriptions in extensions page
Redesign extensions list to see titles and descriptions in full.

New design extensions page

### CODE REVIEW

**Comment by franzliedke** [comment]
@DogSports Please don't change the files in js/dist - we do this after merging (to prevent merge conflicts between multiple MRs).

**Comment by tobscure** [comment]
Happy to merge after js/dist changes are removed from the PR :)

**Comment by TurboProgramming** [comment]
@tobscure Can I do what you wanted to do as @DogSports isn't doing, want this to be done for Beta 8 :)

**Comment by franzliedke** [comment]
@TurboProgramming Sure, go ahead.

**Comment by TurboProgramming** [comment]
@franzliedke I can't edit @DogSports' changes.

**Comment by franzliedke** [comment]
Just create a new PR, please. :smile:

**Comment by TurboProgramming** [comment]
This can be closed as #1496 exists.

**Comment by franzliedke** [comment]
Thanks for getting this started, @DogSports !

**Pull request closed without merging**
