### PR TITLE
Add in admin panel confirm email switch

### LINKED ISSUE #1939: Add in admin panel confirm email switch
## Add in admin dashboard confirm email switch

**Is your feature request related to a problem? Please describe.**
When you have one Website and Forum together, the register of the user will be confirmed by website. It's not necessary be confirmed again by the flarum.

**Describe the solution you'd like**
In admin panel have a switch for a user confirm email.

### PR DESCRIPTION
**Pull request by itsnunolemos**
**Fixes #1939**

**Changes proposed in this pull request:**
Add in admin panel confirm email switch.

**Reviewers should focus on:**
Admin panel and if user receive or not the confirm email.

**Screenshot**
Captura de ecrã 2019-11-19, às 12 29 39

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

**Dependencies**
Translation: [lang-english - PR](https://github.com/flarum/lang-english/pull/150)

### CODE REVIEW

**Comment by luceos** [comment]
Can you clarify when users don't need to verify their mail address? I remember that it's possible to verify new users through the api already and I can't think of alternative scenarios when you would want to skip verification.

**Comment by itsnunolemos** [comment]
In my case the problem is:
I have a website and the user register there and receive the email verification (through website). After user confirm email I send a POST to Flarum API to create this user. If I not remove this verification in Flarum the user needed confirm the email two times.

**Comment by luceos** [comment]
As said. You can disable the need to verify the email address when using the api.

**Comment by itsnunolemos** [comment]
> As said. You can disable the need to verify the email address when using the api.

How?

**Comment by luceos** [comment]
https://github.com/flarum/core/blob/8cc44a695f16feed4e08fbda618fdfb4fbb15afc/src/User/Command/RegisterUserHandler.php#L100-L102

**Pull request closed without merging**
