### PR TITLE
Various UX Fixes

### PR DESCRIPTION
**Pull request by CDK2020**
This PR fixes various UX problems as reported by @ardacebi

* **Fixes** #1484
* **Fixes** #1509
* **Fixes** #1521

### CODE REVIEW

**Comment by datitisev** [comment]
Screenshot of #1509.

image

**Comment by ardacebi** [comment]
Can you include #1506 to this too?

I’ll close that so we’ll have 1 PR for all these issues.

**Comment by datitisev** [comment]
@ardacebi #1506 is your PR and has it's own discussion. There's no reason why multiple PRs are a bad thing, in contrast, multiple PRs let specific changes be merged without changing 50 files and including 20 unrelated features.

**Comment by tobscure** [comment]
Sorry to close this, but please submit one PR per issue, so we can review/merge them individually. In this case, I'd be happy to merge the fix for #1509 straight away, but want to test the one for #1484, and have some comments on #1521.

**Comment by CDK2020** [comment]
@ardacebi no, your PR is fine

**Comment by ardacebi** [comment]
I'm on it if it's okay for everyone.

**Pull request closed without merging**
