### PR TITLE
[A11Y] Explicitly state `aria-hidden` value; hide icons from screenreaders

### PR DESCRIPTION
**Pull request by davwheat**
**Changes proposed in this pull request:**

- Explicitly state the value of `aria-hidden` (needed for Talkback on Android)
- Hide icons from screenreaders as these are purely visual elements

**Reviewers should focus on:**

🤷 

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
  - tested on Android 11

### CODE REVIEW

**Review by SychO9 — APPROVED** [review]

**Review by askvortsov1 — APPROVED** [review]
The string value suffices and we don't need a raw boolean, right?

EDIT: Actually, I think I would prefer using a boolean regardless. It's a bit more explicit as to the intended meaning.

**Comment by davwheat** [comment]
Sure. Mithril converts the boolean to a string when rendering to the DOM, but both ways are fine. I think the boolean might actually be slightly smaller in terms of JS bundle :P

**Comment by davwheat** [comment]
Actually it seems this will not work. Mithril converts the `true` boolean into an empty attribute value as opposed to the string `"true"`, meaning this doesn't fix `aria-hidden` on Android.

**Review by askvortsov1 — APPROVED** [review]
Fair enough. Maybe we should open an issue with Mithril?

**Comment by davwheat** [comment]
No, its intended behaviour.

That way you can set an attribute depending on a conditional, like `checked={this.state.checked}`.

**Pull request merged**
