### PR TITLE
adds heavier validation, also limits to 100 as per database column, a…

### PR DESCRIPTION
**Pull request by Luceos**
…dded some blacklist values for username

Username validation was far too simple. Added some basic values and restrictions based on database column.

### CODE REVIEW

**Comment by tobscure** [comment]
- We should limit usernames to maximum 20-30 characters. 3 minimum is good.

- I don't think this is the right way to go about preventing people from using certain usernames. For one, reserving `admin` will break the vagrant installer. But more importantly, the idea of a blacklist is flawed; you can just work around it by using a similar username (e.g. `mod`, `admin_`, `root-`). If a forum admin has a problem with someone taking a username like that, they can just delete or rename them. There's nothing inherently wrong with using those usernames, so we'll leave blacklisting up to an extension.

**Comment by franzliedke** [comment]
I agree, 30 characters should be good.

**Comment by Luceos** [comment]
Updated:
- removed blacklist items
- limited to between 3 and 30

**Comment by tobscure** [comment]
Please squash the commits and it'll be good to go :D

**Comment by Luceos** [comment]
i guess my rebase failed immensily?

**Comment by franzliedke** [comment]
Yep, please try again :)

**Comment by franzliedke** [comment]
[Did it for you.](https://github.com/flarum/core/commit/68369ac5bb6a1729b34ad8b0a2851c5c9d170626)

**Pull request closed without merging**
