### PR TITLE
#679 Ask for confirmation before "Mark all as Read"

### PR DESCRIPTION
**Pull request by bogdanteodoru**

### CODE REVIEW

**Comment by franzliedke** [comment]
Why the change to the `UpdateUserController`?

**Comment by tobscure** [comment]
@franzliedke The change to `UpdateUserController` looks like it skips the sudo mode requirement if it's only the `readTime` attribute being updated. Which is good, except we actually plan to get rid of sudo mode before beta 5 drops due to some unforeseen complications (see #674). @bogdanteodoru, could you please revert that addition? Otherwise it looks good to merge! :+1:

**Comment by bogdanteodoru** [comment]
@tobscure, done. Please remember to merge the language pull request as well.

**Comment by tobscure** [comment]
Beautiful, thanks!

**Pull request merged**
