### PR TITLE
#726 Specify text inputs type

### LINKED ISSUE #726: Specify text inputs type
**_1 Upvote**_ for example search inputs type should be 'type="search"' or for color inputs should be 'type="color"', etc

### PR DESCRIPTION
**Pull request by datitisev**
Added input type to 3 inputs total, plus some css because bootstrap breaks Flarum. This fixes #726.

Changes:
- Added type search to search bar (forum)
- Added CSS `box-sizing: inherit !important` to search <input> because bootstrap styles mess up the search box
- Added type color to both color settings in appearance (admin)

If you find more inputs that are **not** type text (even if they don't have attribute) please comment.

### CODE REVIEW

**Comment by franzliedke** [comment]
Thanks, looking good! :+1: 

Not sure about the many changes in the JS dist files. Can you try to update your NPM dependencies (run `npm install` again) and see whether that makes any difference, please?

**Comment by datitisev** [comment]
@franzliedke I've just committed with the `"use strict";`s back. I'll do the same to the rest of the pulls

**Comment by tobscure** [comment]
@datitisev Could you please recompile the JS with the latest NPM dependencies installed? Or if there are still irrelevant changes, just remove the compiled JS from the PR and I'll merge the source files :)

**Comment by datitisev** [comment]
@tobscure Ok, sure. I'll do that now.

**Comment by datitisev** [comment]
@tobscure Done. I removed the dist `app.js`s.
I did it from Github, because I tried to compile it, and it would keep giving me merge errors... 🙄

**Comment by tobscure** [comment]
Unfortunately the removal is still part of the PR though... if I merge, it will delete the app.js files in this repo!

**Comment by datitisev** [comment]
Yeah, that's what I just saw... Should I make a new PR with an updated diff with the latest commits from this repo?

**Comment by tobscure** [comment]
Yeah if you think you can figure it out... otherwise if it's too much trouble I can manually apply the changes :)

**Comment by datitisev** [comment]
@tobscure Done! :)

**Pull request closed without merging**
