### PR TITLE
Extension enable/disable hooks

### PR DESCRIPTION
**Pull request by franzliedke**
**My shot at #1463**

**Changes proposed in this pull request:**
- Introduce a new `LifecycleInterface` that extenders *can* implement. If they do, the interface's methods (`onEnable()`, `onDisable()`) will be called when the extension is enabled or disabled. They make it easy for extenders to bring along custom logic for these lifecycle events, instead of having to write messy event listeners.
- Change the `Formatter` extender accordingly. Nice demonstration of how much cleaner this becomes. We seem to be discovering a nice abstraction. :wink: 
- Remove the additional flushing of the formatter cache being done in the `FormatterServiceProvider`. Extensions using the `Formatter` hook were already setting up these listeners (and now they're doing it via the lifecycle hooks). In fact, this means the cache will only be flushed when actually necessary, because only extensions with a `Formatter` extender will actually cause a flush.

Additional, smaller changes:
- Small refactorings I came across while working in and around the `ExtensionManager`

**Reviewers should focus on:**
- Should these lifecycle callbacks be in an additional "marker interface" or part of the existing `ExtenderInterface`? The current solution means less code for extenders that don't need them, at the price of an `instanceof`.
- Do we need other callbacks at this point? [The ticket](https://github.com/flarum/core/issues/1463) referenced other types ("before uninstall", "updating"), but so far the extenders don't seem to have a use-case for them...

**Confirmed**

- [x] Backend changes: tests are green (run `php vendor/bin/phpunit`).

### CODE REVIEW

**Comment by franzliedke** [comment]
Oh, and there is also [`Flarum\Frontend\RecompileFrontendAssets`](https://github.com/flarum/core/blob/1f0e9b62801ccae8339ed3d66919af8ccbbfe953/src/Frontend/RecompileFrontendAssets.php), which **also** flushes some caches when extensions are enabled / disabled. I guess in the long term these should also be part of an extender - the `Frontend` one, I suppose (conditionally based on whether assets have been registered)?

**Comment by tobscure** [comment]
This looks awesome! Happy with the marker interface, I think it's nicer than having to have these empty methods on the extenders that don't need them (which is the majority).

There is still no way for extensions to define their own custom logic on enable/disable/?other lifecycle events. Did you have a plan for that? Just brainstorming some use-cases:

* When **installed** (enabled for the first time), an extension needs to copy assets into the public folder
* When **updated** (this concept doesn't really exist for extensions atm), an extension needs to copy updated assets into the public folder
* When **enabled**, an extension needs to download a file from somewhere and copy it into the public folder
* When **disabled**, an extension needs to flush some cache not covered by existing extenders?
* When **uninstalled**, an extension needs to delete assets from the public folder

Not the best examples, but I think it highlights the need for us to flesh out how the other lifecycle events actually occur. I think what we probably need to do is to store the extension's version number in the database (settings table?) when it is enabled for the first time ("installed" lifecycle hook), same as how we store Flarum's version number. And then if the version of the extension code is different to that stored in the database, we need to prompt running the extension's migrations and call an "update" lifecycle hook.

> Oh, and there is also [`Flarum\Frontend\RecompileFrontendAssets`](https://github.com/flarum/core/blob/1f0e9b62801ccae8339ed3d66919af8ccbbfe953/src/Frontend/RecompileFrontendAssets.php), which **also** flushes some caches when extensions are enabled / disabled. I guess in the long term these should also be part of an extender - the `Frontend` one, I suppose (conditionally based on whether assets have been registered)?

Yep, that would make sense I think.

**Comment by franzliedke** [comment]
Regarding custom logic: At this point, it would be very easy to add a `CustomLifecycle` extender (obviously with a better name) for exactly this use-case.

**Comment by CDK2020** [comment]
Man, from an extension developer's standpoint, this is amazing. Thanks for your hard work @franzliedke. 

1+ for the extra events from Toby though.

**Pull request merged**
