### PR TITLE
illuminate/laravel 5.7

### LINKED ISSUE #1640: Upgrade to Laravel 5.7
We're currently on Laravel 5.5, which is an [LTS release](https://laravel.com/docs/5.7/releases#support-policy). But I think we should still try to keep on the latest? It shouldn't be a huge amount of work to upgrade by the looks of it.

https://laravel.com/docs/5.6/upgrade
https://laravel.com/docs/5.7/upgrade

### PR DESCRIPTION
**Pull request by luceos**
**Fixes #1640**

**Changes proposed in this pull request:**

- Upgrade to Illuminate 5.7
- Make Gates compliant to contract

**Reviewers should focus on:**

- [x] Do we want to keep using the Gate contract, from looking at User\Gate I see a bunch of unused methods which make using the interface pretty much useless.
- [x] Blocked by https://github.com/laravel/framework/issues/26833

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `php vendor/bin/phpunit`).

**Required changes:**

- [ ] ~~Related documentation PR: (Remove if irrelevant)~~
- [ ] ~~Related core extension PRs: (Remove if irrelevant)~~

### CODE REVIEW

**Comment by franzliedke** [comment]
I guess we don't really need the manager class anyway, we can just instantiate the log driver we want to use manually.

**Comment by tobscure** [comment]
> Do we want to keep using the Gate contract, from looking at User\Gate I see a bunch of unused methods which make using the interface pretty much useless.

We will revamp the authorisation code separately soon, but for now this is fine :)

**Comment by luceos** [comment]
Not sure yet. I like to run these changes with a working test suite. 

@franzliedke the problem is that our tests use the Mail driver `log` which resolves `LoggerInterface` from the container. This interface is bound to our Monolog logger and not the Logging Transport manager as Laravel assumes.

Some of our options:

- Rewrite tests to not use the mail driver log and optionally disallow people from using it in Flarum.
- Wait for the changes to be released under 5.7.18, https://github.com/laravel/framework/pull/26842

**Comment by luceos** [comment]
5.7.18 and .19 are tagged, moving forward.

**Comment by luceos** [comment]
Final decision has to be made about the Gate contract and or User/Gate implementation, it now has 5 methods which are not implemented.

Everything else seems 👍 good to go.

**Comment by franzliedke** [comment]
> Final decision has to be made about the Gate contract and or User/Gate implementation, it now has 5 methods which are not implemented.

If I understood [Toby](https://github.com/flarum/core/pull/1698#issuecomment-447124485) right, he wants to take care of revamping `Gate` and other authentication stuff later, so just adding the empty stub is fine.

**Pull request merged**
