### PR TITLE
Fix permission icon width in admin area

### LINKED ISSUE #2016: Make permission icons fixed width
## Bug Report

**Current Behavior**

Differently sized FA icons cause text to be misaligned on the permissions grid:

**Expected Behavior**

Apply class `fa-fw` to give all icons a fixed width, to prevent this misalignment.

This could be a default class which icons have in the Permissions Grid, in addition to the icon class itself defined in the extension's JS.

**Screenshots**

## After

**Environment**
- Flarum version: 0.1.0-beta.11.1
- Website URL: (local)
- Webserver: apache
- Hosting environment: local (xampp)
- PHP version: 7.3.14

### PR DESCRIPTION
**Pull request by tankerkiller125**
**Fixes #2016**

**Changes proposed in this pull request:**

Uses the Font Awesome fixed width helper to make all icons the same width so that text aligns

**Reviewers should focus on:**

* Is this the best way of doing this? Or is there some other way that I missed?

**Screenshot**

The screenshots in #2016 clearly show the diffrence

**Confirmed**

- [X] Frontend changes: tested on a local Flarum installation.

### CODE REVIEW

**Comment by davwheat** [comment]
I'm definitely not a reviewer, but I think this is the best way to go about it.

There's no real reason that an extension would want to make their permission icon not be fixed width, as far as I can think of.

**Comment by tankerkiller125** [comment]
the only thing I can possibly think of is if an extension for some reason uses it's own icon library

**Comment by askvortsov1** [comment]
> the only thing I can possibly think of is if an extension for some reason uses it's own icon library

In that case, the added CSS class should have no effect, I think this is fine!

**Comment by davwheat** [comment]
Brilliant!

**Comment by franzliedke** [comment]
> the only thing I can possibly think of is if an extension for some reason uses it's own icon library

This was a good point, so I [fixed this slightly differently](https://github.com/flarum/core/commit/922e29466814ecb3968158badb7ead92f4fafc2f) by applying the fixed width to our existing CSS for these icons (along with some additional cosmetics). This should be completely independent of icon library (or future FontAwesome upgrades).

Thanks for bringing it up @davwheat and thanks for the PR @tankerkiller125 !

**Pull request closed without merging**
