### PR TITLE
Updates s9e/text-formatter to 2.x

### LINKED ISSUE #1979: Upgrade s9e/text-formatter
Creating this ticket so we don't lose it in the forums.

## Upgrade Request
s9e/text-formatter is very behind currently (^1.2.0, current version is 2.2.3) an upgrade should be made to bring this up to date and determine what has changed so that the upgrade can be performed. The new version brings in several enchantments (such as customization over code highlighting)

### PR DESCRIPTION
**Pull request by tankerkiller125**
**Fixes #1979**

**Changes proposed in this pull request:**

Updates s9e/text-formatter to the latest version, no changes other than `composer.json` were needed, tested all functionality still works and extensions such as `fof/formatting` still work as intended.

**Reviewers should focus on:**

- Should this be in the beta.12 release or a following update
- Any breaking changes I might have missed (tested emoji, fof/formatting, mentions, markdown and bbcode all working)
- Please note that this change adds new markdown support (notably spoilers) when markdown extension enabled.

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

**Comment by luceos** [comment]
While deploying to discuss we encountered an issue in firefox. Possibly xslt is not supported in this browser, did that version update to 2 perhaps? We might need a polyfill for that.

**Comment by tankerkiller125** [comment]
The following link is a side by side comparison of the render.js of s9e/text-formatter, on the left is the old one and on the right is the new one. https://gist.github.com/tankerkiller125/041361820156f76e0426bdf1e000429c/revisions I'm combing through but I've been unable to find where/why it might be erroring.

**Comment by askvortsov1** [comment]
Maybe we could add in the Saxon JS runtime as a workaround? http://www.saxonica.com/saxon-js/index.xml

**Comment by luceos** [comment]
Can either of you do a test with saxon as a solution? We can check whether that's wanted or not in the PR.

**Comment by askvortsov1** [comment]
I can do so later today and report back

**Comment by askvortsov1** [comment]
After some experimentation, I'm not entirely sure that xlst2 is the issue (it doesn't look like s9e/text-formatter changed to it?) I'm running a local installation of beta 12 with only bundled extensions installed, and everything works fine for me on Firefox. @luceos what version of firefox were you able to reproduce this with? I'll try running with that, as well as installing all the Discuss extensions and seeing whether that changes anything.

**Comment by tankerkiller125** [comment]
@askvortsov1 I also see the issue on Firefox 73.0.1 you can see it on https://nightly.flarum.site possibly.

**Comment by luceos** [comment]
72.0.2 (64-bit)

**Comment by tankerkiller125** [comment]
It looks like it may be related to sentry?
image
But I'm not sure, this may just be because it's erroring before sentry initializes.

**Comment by askvortsov1** [comment]
I'm running the same firefox, and it's working fine on the bare-bones local install. Can we try disabling sentry/other extensions on nightly?

**Comment by luceos** [comment]
We have protection in place to prevent the removal of sentry on the demo sites. 🤔

**Comment by askvortsov1** [comment]
the odd thing is, the first error log in Matt's screenshot (the one's that just a colon) originates in s9e's library. Possibly the error is handled somewhere else in s9e, but sentry tries to report it and fails, and that blocks rendering of the buttons?

**Comment by tankerkiller125** [comment]
Just tested without sentry, on Firefox 73.0.1, complete error, no tags list, we may need to revert until this issue gets fixed by the text-formatter lib.

**Comment by luceos** [comment]
@JoshyPHP is this something you encountered before? https://nightly.flarum.site with firefox. Seems somewhere this browser is not supported.

**Comment by JoshyPHP** [comment]
No, I've never heard of an issue related to a single colon. I read the comments but I haven't seen anything about the actual error. Is there an error message somewhere?

The templates use the same XSLT 1.0 as before.

**Comment by tankerkiller125** [comment]
@JoshyPHP We're just seeing the colon error, nothing more. Upon loading in Chrome I'm able to access the s9e.TextFormatter global functions but on Firefox I can not. Even with webpack dev mode I'm unable to find the exact location of the error with the JS maps.

**Comment by JoshyPHP** [comment]
I looked into it and the error message is caused by Firefox's XPath lexer which has difficulties parsing some expressions.

As a temporary workaround, you can manually alter the template used for `[list]` with this:
```php
$configurator->tags['list']->template = str_replace('or', '+', $configurator->tags['list']->template);
```

**Comment by askvortsov1** [comment]
This seems to be a pervasive issue throughout the site (for example, this also breaks the reply/like links at the bottom of each post). I'm not sure that it would be feasible to manually patch around every instance, especially when some of them might be in 3rd party extensions

**Comment by tankerkiller125** [comment]
@askvortsov1 patching the BBCode extension resolved all issues in my dev environment.

@luceos I've created a patch to the BBCode extension https://github.com/flarum/bbcode/pull/9

**Comment by JoshyPHP** [comment]
@tankerkiller125 Don't patch the extension, I'll fix the issue in my library directly and release 2.3.5 later today.

**Comment by tankerkiller125** [comment]
@JoshyPHP even better :)

**Comment by tankerkiller125** [comment]
I've just tested with the latest version of text-formatter and everything is working as expected now on Firefox, thanks @JoshyPHP

**Comment by luceos** [comment]
@JoshyPHP thanks for hopping into this so fast 🤗 

@tankerkiller125 feel free to PR the minimum constraint for 2.3.6 if you want.

Great job!

**Pull request merged**
