### PR TITLE
deprecations and type hinting

### PR DESCRIPTION
**Pull request by luceos**
removes some deprecated code and adds some type hinting compliant with php 7.0

### CODE REVIEW

**Comment by tobscure** [comment]
I have just fixed this issue in an alternative way by upgrading everything to PSR-15 / stratigility 3.0, will PR later today. Thanks though :)

**Comment by franzliedke** [comment]
See [my comment on that PR](https://github.com/flarum/core/pull/1404#issuecomment-380350809), I am not convinced we should use Stratigility 3.x.

**Comment by luceos** [comment]
I guess we can move forward by merging this one as well then?

**Comment by franzliedke** [comment]
This will be made obsolete when I finish #1416.

**Pull request closed without merging**
