### PR TITLE
Remove hosted s9e minifying service as it is down

### PR DESCRIPTION
**Pull request by gwillem**
See also #887 and

https://discuss.flarum.org/d/1870-new-javascript-minifiers

### CODE REVIEW

**Comment by gwillem** [comment]
I'd humbly suggest to only commit CI-validated code :D

**Comment by gwillem** [comment]
Dropping the Google Closure Service drops another 10s off my isolated vagrant benchmark.

**Comment by gwillem** [comment]
Made a small benchmark for Matthias Mullie's Minify. My standard Flarum install has about 45K lines. As you can see, there's a sharp rise at about 34K lines. TL;DR: with the growing amount of JS, we might look for a faster JS minifier :D

minifier-benchmark

**Comment by gwillem** [comment]
@franzliedke I rebased on master, could you reopen this? I can't...

**Comment by franzliedke** [comment]
@gwillem Thanks a lot. This is now obsolete, as Toby's [move to WebPack](https://github.com/flarum/core/pull/1367) takes care of minifying.

**Pull request closed without merging**
