### PR TITLE
Fix login box autocomplete in firefox

### LINKED ISSUE #467: Unable to log in via KeePassX autotype
There is something funky in the Flarum login form that stops it accepting auto-type from KeePassX.

Browser: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.2.0
OS: Debian Jessie
KeePassX: 0.4.3

To reproduce:

Create a KeePassX site entry for Flarum, with a valid Flarum username and password, and the URL http://discuss.flarum.org/

In KeePassX, double-click the URL of the Flarum entry and wait for the browser to open the Flarum main page.

Click Login. Verify that the insertion point is correctly positioned in an empty Username or Email box.

Bring the KeePassX window to the front again, and press Ctrl-V to make KeePassX auto-type username, Tab, password, Enter into the browser window.

Expected result: Login form appears to be filled in and Flarum logs on.

Actual result: White flicker at bottom of browser window, nothing appears in logon form text boxes, logon doesn't happen.

I have credentials for several hundred sites in my KeePassX database. Flarum is the only one that displays this behavior.

No repro on Chromium.

### PR DESCRIPTION
**Pull request by sijad**
use [oninput](http://caniuse.com/#feat=input-event) event fixes ~~#467~~ and #698

### CODE REVIEW

**Comment by sijad** [comment]
as I don't have access to debian os I can't be sure if #698 has been fixed...

**Comment by franzliedke** [comment]
Can you explain why this fixes the issue?

**Comment by bmalex88** [comment]
With `autocomplete="off"` for the text inputs this problem is solved, I think. Using `oninput` event is also an improvement, as it only fires when text is changed

**Comment by sijad** [comment]
@franzliedke in FF when you select and click on you email from autocomplete form, FF only fire `change` event for `password` input and not for 'email'
when this happens `this.email` stay empty and as Mithril do redraw the `Modal` it only fill `password` input

**Comment by franzliedke** [comment]
Okay, I guess that's fine then. :+1: from me.

**Comment by tobscure** [comment]
The issue with using `oninput` is that if redraws are slow (perhaps due to lots of things being on the page, behind the modal), then typing becomes slow.

What we should probably do is call `m.redraw.strategy('none')` when setting the field values in the `oninput` handler – this way it will update the component state, but won't trigger a redraw (which is unnecessary anyway).

**Comment by tobscure** [comment]
...However, until this causes visible problems with performance, I think it's nicer to use `bidi` as I have done in 71d2e71908de6051b8ae7f29bae4c4e3e14e88f6 :P

**Comment by sijad** [comment]
@tobscure sorry about that, I didn't know about `bidi`

**Pull request merged**
