### PR TITLE
Upgrade to jQuery 3.1.1

### LINKED ISSUE #979: Upgrade to jQuery 3.0
https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/

We can probably use the slim version.

### PR DESCRIPTION
**Pull request by sijad**
closes #979

### CODE REVIEW

**Comment by sijad** [comment]
I'm wonder why in `js/admin/dist/app.js` `3,201 additions, 4,304 deletions` has been done and in `js/forum/dist/app.js` `3,304 additions, 4,407 deletions`, did I miss something?

**Comment by tobscure** [comment]
Sorry @sijad I just split `next` into `next-front` and `next-back` so we can work on frontend/backend changes separately. Could you please resubmit this to `next-front`?

**Comment by sijad** [comment]
I can't reopen it but it's on `flarum:next-front` now

**Comment by Magicalex** [comment]
Have you test your commit? I have some problems with jquery.
Exemple method .bind() are deprecated with jquery 3 for method .on()

**Comment by sijad** [comment]
sorry I didn't pay attention deprecated codes has been removed from slim version.

**Pull request merged**
