### PR TITLE
Fix code in RouteNotFoundException

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by franzliedke** [comment]
Can you explain these changes, please?

**Comment by WinterSilence** [comment]
@ franzliedke fix http://bugs.php.net/39615

**Comment by franzliedke** [comment]
I saw that link in the code. Can you please show an example how our current code is actually broken, though?

**Comment by WinterSilence** [comment]
Some exceptions contain _code_ as string (PDOException::getCode()), It's add multitype codes. 
~~~
try {
    $pdo->query('CHECK ROUTE - BAD QUERY');
} catch (PDOException $e) {
    // FAIL!
    throw new RouteNotFoundException($e->getMessage(), $e->getCode());
}
~~~

**Comment by Luceos** [comment]
I feel this is something that the framework (laravel) should take care of, not flarum.

**Comment by WinterSilence** [comment]
@Luceos `RouteNotFoundException` not extend laravel exception

**Comment by tobscure** [comment]
@WinterSilence I think what @franzliedke is saying is, what **reproducible, tangible bug in Flarum does this fix**? Nowhere do we pass a PDOException's code into a RouteNotFoundException.

**Comment by WinterSilence** [comment]
@tobscure ok, close PR and extends laravel exception

**Pull request closed without merging**
