### PR TITLE
Update UserCard.less file

### PR DESCRIPTION
**Pull request by malayladu**
+ Add color #7FBA00 for online user - https://github.com/flarum/core/issues/254

### CODE REVIEW

**Comment by franzliedke** [comment]
Can you post a screenshot?

**Comment by tobscure** [comment]
I fear this might not look so great on some background colors. We should probably give it a 1px `@body-bg` border too, like badges.

**Comment by malayladu** [comment]
Sure..here you go.

flarum-profile

**Comment by franzliedke** [comment]
Also... should this use a variable, @tobscure?

**Comment by malayladu** [comment]
@tobscure You are right. It won't look good in all background. How about keeping profile background white only?

**Comment by tobscure** [comment]
Actually, this PR isn't even working at all. Should be `&.online` without the space (because the `online` class is applied to the same element). Also, the color should only be on the icon, not the text. I just tried it out and it should actually look OK on various background colors - no need for a border.

@franzliedke Yeah good point, it should.

**Comment by malayladu** [comment]
@tobscure Aha ok..

I am new to less and flarum structure. Just want to know how to compile .less css in Flarum to test whatever changes  I have made into actual .css files?

**Comment by tobscure** [comment]
Delete the *.css files in your assets directory and Flarum will recompile.

Please test changes and make sure they work as intended *before* submitting a PR in the future :)

**Comment by malayladu** [comment]
@tobscure Thanks for the info.

I will make sure that.

**Comment by malayladu** [comment]
This is better now.

malayladu - discuss

**Comment by tobscure** [comment]
Looks good to me. Happy with this @franzliedke?

**Comment by tobscure** [comment]
Oh, actually @malayladu we'll need you to [squash those commits](http://davidwalsh.name/squash-commits-git) before we merge.

**Comment by franzliedke** [comment]
If you could use a variable for the color, this could fly. :airplane:

**Comment by malayladu** [comment]
@franzliedke This is done

**Comment by malayladu** [comment]
@franzliedke Added variable instead of color code

**Comment by franzliedke** [comment]
Great! Now if you could squash these commits as Toby suggested, we're done. :)

(Whew. What a long discussion for such a small change. Thanks for being patient!)

**Comment by malayladu** [comment]
@franzliedke Sorry..I don't know how to Squash commits..I am using Source Tree for mac.

**Comment by franzliedke** [comment]
Both Toby's link and [this help document](https://answers.atlassian.com/questions/213902/in-sourcetree-how-do-i-squash-commits) explain how it works. :)

**Comment by malayladu** [comment]
@franzliedke I have done it.

**Comment by franzliedke** [comment]
Now you need to force push. :)

**Comment by malayladu** [comment]
@franzliedke  I have done that too :) What else I have to do? Sorry @franzliedke , I am taking too much of your time but I won't take next time onward. New to Github :)

**Comment by franzliedke** [comment]
That [didn't work](https://github.com/flarum/core/pull/452/commits), apparently. Execute this in your command line: `git push origin --force`

And no worries, we'll gladly help you learn. Thanks for contributing!

**Comment by malayladu** [comment]
@franzliedke I have done. Please check below image.
flarum-core bash 148x36

**Comment by franzliedke** [comment]
Now we have six commits. That must mean the squashing didn't work... just do it on the command line by following [this tutorial](http://davidwalsh.name/squash-commits-git). It's really not complicated. :)

**Comment by franzliedke** [comment]
Okay, I [committed this for you](https://github.com/flarum/core/commit/b05f83d25a5ef1267d8d973013143c61295cdc50).

Thanks again!

**Comment by malayladu** [comment]
@franzliedke Thanks for your help.

I followed that tutorial also but it didn't work for me.

Anyways, I will dig into that and figure out why it didn't work. it will be helpful for future.

**Pull request closed without merging**
