### PR TITLE
Change Zend namespace to Laminas

### PR DESCRIPTION
**Pull request by tankerkiller125**
**Fixes #0000**

**Changes proposed in this pull request:**

Changes Zend namespace to Laminas to reflect the recent name change of the Zend Framework

**Reviewers should focus on:**

- Did I find all the Zend usages?

**Screenshot**

**Confirmed**

~~- [ ] Frontend changes: tested on a local Flarum installation.~~
- [X] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

**Comment by franzliedke** [comment]
Thanks for tackling this!!!

We do have a small problem, though, and that is extensions [using some Diactoros classes](https://github.com/flarum/auth-facebook/blob/6a9454954c5d45aa6544d3729b41ff2eb0deb460/src/FacebookAuthController.php#L22). They would have to switch to Laminas to be compatible with the next beta - which is something we are trying to avoid - for one beta cycle. Unfortunately, not even our bundled extensions have explicitly declared the dependency - they just trust that flarum/core will include it.

Is it possible to load both dependencies? We can then use Laminas everywhere in our code, and remove the old Zend dependencies for beta.13. That will give extensions one release cycle time to switch over, with both the new and old code working.

**Comment by datitisev** [comment]
@franzliedke Laminas has a package that should allow the use of ZendFramework classes with Laminas, see [laminas/laminas-zendframework-bridge](https://github.com/laminas/laminas-zendframework-bridge)

**Comment by tankerkiller125** [comment]
@datitisev Based on reading through that code package it appears that we should be able to add it as a composer dependency along with the Laminas changes proposed here and it should protect backwards compatibility. I'll see if I can test tonight or tomorrow to ensure that that statement is correct.

**Comment by tankerkiller125** [comment]
I've added the Laminas bridge as a dependency in core, it works exactly as expected (generating autoload classes that just reference Laminas) this should resolve any backwards compatibility issues for beta.12 and the package can then be removed in beta.13 (breaking the Zend namespace) this is definitely something we will want to make sure to publish in the changelog for developers.

**Comment by franzliedke** [comment]
I see the following follow-ups:
- [ ] a ticket for removing the BC layer, targeted for beta.13
- [ ] update bundled extensions to use the new namespaces
  - [ ] auth-facebook
  - [ ] auth-github
  - [ ] auth-twitter
  - [ ] pusher
  - [ ] tags
- [ ] update the docs: `docs/extend/routes.md` references old namespace

@tankerkiller125 Can you take care of these, too? :pray:

**Comment by tankerkiller125** [comment]
@franzliedke I'll take care of those, labels/milestone for the ticket will have to be added by someone else (no access) https://github.com/flarum/core/issues/1964

**Comment by luceos** [comment]
Milestone modified for #1964

**Comment by franzliedke** [comment]
I like how all of these extension PRs had ever-so-slightly different description texts. :rofl: 

In all seriousness: thanks for taking care of this, and so swiftly!

**Pull request merged**
