### PR TITLE
Fix #834

### LINKED ISSUE #834: getPlainContent does not trim spaces from either end
[getPlainContent](https://github.com/flarum/core/blob/232f3b6bc696f8c36b39b1eeaae01c299d4a1622/js/lib/utils/string.js#L36) is leaving in extra spaces when it replaces html elements.

### PR DESCRIPTION
**Pull request by dav-is**
This fixes #834 

First, I change all <img tags to <eximg to prevent loading them as images.

Then, I added something to remove extra spaces. It replaces groups of spaces between non space characters with a single space. I also replaces spaces between the first (or last) space and a non space character. This effectively allows only one space between characters.

### CODE REVIEW

**Comment by datitisev** [comment]
@dav-is What about the image closing tab?
It may give an error in some old browsers :/
If you open something, make sure you close it :wink:

**Comment by dav-is** [comment]
@datitisev I have no idea what you're talking about

**Comment by franzliedke** [comment]
@datitisev `` is self-closing.

**Comment by dav-is** [comment]
@datitisev Oh. The closing **tag**

**Comment by datitisev** [comment]
@dav-is @franzliedke Sorry, it was late & autocorrect :cry:

Pardon my useless comment

**Comment by tobscure** [comment]
Tweaked and merged, thanks :)

**Pull request closed without merging**
