### PR TITLE
Only translations for enabled extensions should be loaded from language pack

### LINKED ISSUE #1837: Only translations for enabled extensions should be loaded from language pack
According to [this discussion](https://discuss.flarum.org/d/19971-extensions-translation-in-their-own-repository-or-in-language-pack), translations of extensions should be in language packs instead of extensions itself. I worked recently to make this approach more convenient for translators, but there is still a performance issue with it. 

Right now Flarum loads all translations from language packs, so if I install a language pack with translations for 1000 extension, Flarum will load all 1k translation files even if I don't need 970 of them. I'm not sure how heavy this is from PHP side, but translations are also included in the generated JS file, so this may result in a huge JS file (full of unnecessary translations) which will slow down page load.

I suggest loading only translation files with names that match the ID of one of the installed extensions (+core files). This change may break some language packs which does not follow this convention, so this probably should be addressed in beta 10.

### PR DESCRIPTION
**Pull request by rob006**
fixes #1837
replaces #1954

This is continuation of #1954. I fixed condition for detecting core files (`validation.yml` and `core.yml`) and tested this locally - it is working as expected.

### CODE REVIEW

**Comment by rob006** [comment]
OK, I found one problem. Extensions that use translations but does not register `Locales` extender, does not trigger locale cache refresh after enabling/disabling the extension - user needs to refresh cache manually to load translations for these extensions. This affects only core extensions - they have their translations in https://github.com/flarum/lang-english/tree/master/locale. Every other extension has bundled English translation and register it using `Locales` extender.

I'm not sure how to proceed with this. Personally, I would just move these translation files to extensions, like in every other 3rd party extension - it seems to be more consistent and pragmatic (you don't need to open 2 PRs every time you add a new setting to extension, and you can release extensions and language pack independently).

**Comment by askvortsov1** [comment]
Is there a reason why core extensions don't use Locales? @core team

**Comment by tankerkiller125** [comment]
I'm personally in favor of moving translations to their respective extensions.

**Comment by askvortsov1** [comment]
I would agree, that should make development a bit less complex imo.

**Comment by askvortsov1** [comment]
> I'm personally in favor of moving translations to their respective extensions.

Should this be split into a separate issue?

**Comment by rob006** [comment]
> I'm personally in favor of moving translations to their respective extensions.

Another reason to do this is that English fallback (#1961) will not work for these extensions, since there will be no English translations available (unless you have English language pack installed and enabled).

**Comment by clarkwinkelmann** [comment]
Suggestion: call the Locale extender in each of the core extensions even if they have no locales files so that they clear the cache. That way we can ship this bug-free without having to make an immediate discussion on whether we move language files out of the English pack.

Maybe we need an additional method on the Locale extender so that we can register an empty locale file list without having to create an empty `locales` folder.

**Comment by franzliedke** [comment]
We just talked about this in our dev meeting.

- We agree with the approach.
- We want to discuss translations for bundled extensions in a separate issue (#2090) in time for the stable release.
- For bundled extensions, the problem currently isn't solved. IMO, that's not a huge problem. We can ignore that (as #2090 may solve it, too). or go with Clark's approach.

---

> Maybe we need an additional method on the Locale extender so that we can register an empty locale file list without having to create an empty locales folder.

@clarkwinkelmann I think that won't be necessary. For the current code in the extender, *any* directory without YAML files should do - and it might even work with non-existing directories. :grin:

**Comment by tomsgad** [comment]
> We just talked about this in our dev meeting.
> 
> * We agree with the approach.
> * We want to discuss translations for bundled extensions in a separate issue (#2090) in time for the stable release.
> * For bundled extensions, the problem currently isn't solved. IMO, that's not a huge problem. We can ignore that (as #2090 may solve it, too). or go with Clark's approach.
> 
> > Maybe we need an additional method on the Locale extender so that we can register an empty locale file list without having to create an empty locales folder.
> 
> @clarkwinkelmann I think that won't be necessary. For the current code in the extender, _any_ directory without YAML files should do - and it might even work with non-existing directories. 😁

I am still getting the same error, I have just added beta-12, all I get is keys e.g, core.forum.discussion_list.empty_text. Any suggestions on how I can fix this for now?

**Comment by askvortsov1** [comment]
> I am still getting the same error, I have just added beta-12, all I get is keys e.g, core.forum.discussion_list.empty_text. Any suggestions on how I can fix this for now?

This is most likely unrelated to this pull request, which is good, since you probably don't need to wait for Beta 13 to fix it! I suspect that you're also the one who replied on https://discuss.flarum.org/d/19684-missing-translations-flarum-shows-translation-id based on the profile picture and timing. I'll respond there as discuss is a better place for support.

**Comment by franzliedke** [comment]
Possible follow-up tasks for interested people (hint hint @rob006 @clarkwinkelmann @askvortsov1):

**Updates for bundled extensions**
If we want to fix this for the bundled extensions (I don't care too much), feel free to send PRs to all bundled extensions (*except for the English language pack*) with the following:

1. A new file `locale/.keep`.
2. A new line `new Extend\Locales(__DIR__ . '/locale'),` in the extension's `extend.php` script.

**Documentation update**
The *convention* on how to name translation files is now a stricter requirement, if I get this right. So we should mention this [in the documentation](https://flarum.org/docs/extend/i18n.html#registering-locales).

**Pull request merged**
