### PR TITLE
Export all missing modules in compat

### PR DESCRIPTION
**Pull request by DavideIadeluca**
**Fixes #0000**

**Changes proposed in this pull request:**
Export all missing modules with the Compat API and therefore improve the extensibility of the framework.

**Reviewers should focus on:**
We need to make sure that those exports are adopted in the 2.x equivalent (`forum.ts`). I suggest that the export registry upgrade step is used just before the first 2.0 beta is released.

**Screenshot**

**QA**
1. Try to extend/override a newly added component from core
2. Try to extend/override a newly added component from an extension
3. Try to use a newly added util which is the default export (i.e. `fireDebugWarning`)
4. Try to use a newly added util which is a non default export (i.e. `fireDeprecationWarning`)

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

**Comment by imorland** [comment]
@DavideIadeluca what's the progress on this one, are you able to complete this soon-ish?

**Comment by DavideIadeluca** [comment]
> @DavideIadeluca what's the progress on this one, are you able to complete this soon-ish?

I just did a round of testing and everything seems to be in order.  The CI is failing, but it doesn't appear to be related to the changes I made.

PR is ready for review from my side now.

**Review by imorland — APPROVED** [review]
Thank you for this, I'll include it in the upcoming `1.8.6` release

**Comment by imorland** [comment]
Ps, would you mind doing the same for `2.x` when you have the chance, please?

**Comment by DavideIadeluca** [comment]
> Ps, would you mind doing the same for `2.x` when you have the chance, please?

Yes, sure I can. I suggested doing it just before the first beta is released in case new components/utils are added/removed etc. and forgotten to be added in `forum.ts`. But I'm happy to do it anyway in the next coming days.

**Comment by imorland** [comment]
I am reverting this until we can resolve the js typings errors in the CI..

@DavideIadeluca can you possibly take a look at this when you can?

**Pull request merged**
