### PR TITLE
Fixed avatar upload

### PR DESCRIPTION
**Pull request by TheOfficialDoc**
https://discuss.flarum.org/d/3969-cant-upload-avatar-debug-file-inside

### CODE REVIEW

**Comment by TheOfficialDoc** [comment]
Tried it on my flarum and it worked dont know why these checks are saying no :/

**Comment by TheOfficialDoc** [comment]
Knows Issues:

If you are using cloudflare you must clear cache to change avatar

(or set expiration cache to 2 hours so it will update every 2 hours - 2 hours is lowest)

**Comment by milescellar** [comment]
Checks failed because of a StyleCI coding recommendation. Change your code to:
```php
$tmpFile = $tmpFile.'.jpg';
```

**Comment by TheOfficialDoc** [comment]
Oh yeah I see it now

**Comment by dav-is** [comment]
This should be closed.
https://github.com/flarum/core/commit/006ea022270ed50c67d7b22cbeb99f123719f3c2

**Pull request closed without merging**
