### PR TITLE
Remove extension generator

### LINKED ISSUE #1045: Drop skeleton generator for now
Let's drop the skeleton generator for now. Switching to composer driven stack has made the command non-functional. 

See original issue #915

If @franzliedke or @sijad could take of this, that would be great! Please acknowledge.

### PR DESCRIPTION
**Pull request by sijad**
fixes #1045

### CODE REVIEW

**Comment by Luceos** [comment]
@sijad thank you, assigned the Merge Master to this PR.

**Comment by franzliedke** [comment]
Thank you!

**Comment by tobscure** [comment]
Thanks!

**Comment by sijad** [comment]
I missed https://github.com/flarum/core/blob/master/.gitattributes#L3

**Comment by Luceos** [comment]
done, thanks @sijad !

**Pull request merged**
