### PR TITLE
Add discussion_id foreign key to posts table

### LINKED ISSUE #1909: Posts are not permanently deleted when permanently deleting discussions
## Bug Report

**Current Behavior**
When one permanently deletes a discussion, their posts remain in the DB but cannot be seen.

This can & has caused issues with flarum/flags and other extensions that get the post's discussion without checking for it first.

**Steps to Reproduce**
1. Create a discussion with posts
2. Permanently delete discussion
3. Look at DB, posts remain

**Expected Behavior**
The discussion's posts should also be permanently deleted.

**Possible Solution**
Most likely add an `onDelete` clause to the foreign key (or create a foreign key if it doesn't exist)

### PR DESCRIPTION
**Pull request by datitisev**
**Fixes #1909**

**Changes proposed in this pull request:**
Create foreign key for `discussion_id`, cascade on delete.

**Confirmed**

- ~~Frontend changes: tested on a local Flarum installation.~~
- [x] Backend changes: tests are green (run `composer test`).

### CODE REVIEW

**Comment by datitisev** [comment]
Looks like some tests create posts without them having a discussion, so they now fail as an existing discussion is required... 🤔

**Comment by datitisev** [comment]
I was able to fix the failing tests. It just required reordering the table inserts, but for it to work I had to remove the `first_post_id` value as the discussion needs to be created first.

This can be fixed by using `prepareDatabase` and not caring about the foreign key constraints while we add the discussions & posts...

Do we want a test in the `DeleteDiscussionControllerTest` that checks that the post is deleted (checking foreign key `on delete` works)?

**Comment by luceos** [comment]
> Do we want a test in the DeleteDiscussionControllerTest that checks that the post is deleted (checking foreign key on delete works)?

I'd say yes.

**Comment by datitisev** [comment]
I have done a test thingy, not sure if this is how I should've done it because there aren't many tests that aren't simple GET requests...

Seems to work, `find` returns `null` because the post no longer exists in `posts`.

**Pull request merged**
