### PR TITLE
remove cache files from storage/views, when cache clear command is ex…

### PR DESCRIPTION
**Pull request by emamulkhan**
remove cache files from storage/views, when cache clear command is executed and also when a extension is enabled/disabled

**Fixes #0000**
2630 - https://github.com/flarum/core/issues/2630

**Changes proposed in this pull request:**

**src/Extend/View.php**
added OnEnable and OnDisable methods - to clear cache files from storage/views folder when an extension is enabled or disabled from admin

**src/Foundation/Console/CacheClearCommand.php**
added a line of code to remove cache files from storage/views folder 

**Reviewers should focus on:**
Testing if the cache files are removed from storage/views when cache clear command is executed and when an extension is enabled/disabled

**Screenshot**

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

**Review by askvortsov1 — CHANGES_REQUESTED** [review]
Thank you for the PR! There's a lot of file mode changes, please revert those

**Comment by emamulkhan** [comment]
You're welcome, do you mean to say file permissions? if yes, what should be the mode 755 ?

**Comment by askvortsov1** [comment]
> You're welcome, do you mean to say file permissions? if yes, what should be the mode 755 ?

It should be whatever it was initially, I believe 644.

**Comment by emamulkhan** [comment]
Changed the mode of files and made it similar to previous one.

**Comment by askvortsov1** [comment]
Hmm, it still think that it's changed... Odd... Try something line https://stackoverflow.com/questions/2517339/how-to-restore-the-permissions-of-files-and-directories-within-git-if-they-have

**Comment by emamulkhan** [comment]
Before pushing the latest commit, what i did to change file mode is, i took the latest clone of core in a separate directory, copied all the files and folders from it  and replaced the previous file and folder inside my apache root directory with the copied one.

After doing this when i checked the file/folder permissions i found that it is similar to the newly cloned one

I am just wondering now how can i use the suggestions given in above stackoverflow link

**Comment by askvortsov1** [comment]
> Before pushing the latest commit, what i did to change file mode is, i took the latest clone of core in a separate directory, copied all the files and folders from it and replaced the previous file and folder inside my apache root directory with the copied one.
> 
> After doing this when i checked the file/folder permissions i found that it is similar to the newly cloned one
> 
> I am just wondering now how can i use the suggestions given in above stackoverflow link

Hmm, looking at it now, it also looks like some unrelated changes got in. My suggestion would be deleting your local core directory, re-cloning it, and re-applying relevant changes based on this PR, then opening a new PR. Before you do this, run `git config --global core.fileMode false` to avoid future file mode issues.

**Pull request closed without merging**
