### PR TITLE
Use revision versioner to allow custom asset versioning

### PR DESCRIPTION
**Pull request by luceos**
**Changes proposed in this pull request:**

Allows asset compilation to use a different version hasher implementation. This allows easier implementation of rev-manifest.json storage locations. Eg on our stack if we override where assets are stored, the rev-manifest.json is stored there too (s3). This causes each request to read from the s3 bucket as well. A better location for something like that would be either the settings table or redis. For normal local-file based Flarum instances, the default rev-manifest handler is sufficient.

**Reviewers should focus on:**

Is this okay?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

**Comment by askvortsov1** [comment]
Makes sense to me, but unfortunately we still have to stick with PHPDocs for class parameters until we fully drop 7.3.

**Review by askvortsov1 — COMMENTED** [review]
Convert the property type to a docblock

**Comment by luceos** [comment]
Habit be bad, will do so asap.

**Comment by luceos** [comment]
> Convert the property type to a docblock

Done, anything else?

**Review by askvortsov1 — APPROVED** [review]

**Review by tankerkiller125 — APPROVED** [review]

**Pull request merged**
