### PR TITLE
Highlight post when linked

### PR DESCRIPTION
**Pull request by bkolobara**
Hi. I'm getting familiar with the flarum codebase and was thinking this is a good first issue (#983) I can pick up. When a post is linked, it is highlighted in orange for 4s. I think this color works well for both, bright and dark theme. I also removed some "dead code" while I was there.

Would love to get some feedback on it.

### CODE REVIEW

**Comment by dav-is** [comment]
Maybe you could add a gif that shows this change's effect?

**Comment by datitisev** [comment]
In my opinion, that doesn't fit Flarum very well, as orange is usually used for important things. I also think it should have some padding on the sides and some border radius.
I think that orange may be too dark, maybe the previous light blue color could be used for the background, but with less opacity.

**Comment by dav-is** [comment]
Why not reuse the animation when hovering over replies?

**Comment by franzliedke** [comment]
Agreed about the reuse suggestion.

For the concrete design (for both), we should probably wait for input from @tobscure.

**Comment by franzliedke** [comment]
That said, thanks for taking this on, @bkolobara! And :clap: for removing the commented code there.

**Comment by tobscure** [comment]
This will be taken care of as part of the updated design that is scheduled for an upcoming release. Thanks for your input though :)

**Pull request closed without merging**
