### PR TITLE
401 for unauthorised request to settings, notifications page

### PR DESCRIPTION
**Pull request by sijad**
***1 Upvote***

### CODE REVIEW

**Comment by tobscure** [comment]
I think it would be better to make a new subclass of ClientController for settings/notifications (`AuthorizedClientController`?), and put the auth check in there.

**Comment by sijad** [comment]
should we add a new `Flarum\Http\Exception`? like `RouteNotFoundException`

**Comment by tobscure** [comment]
You can just use Flarum\Core\Exception\PermissionDeniedException

**Comment by sijad** [comment]
done, sorry for giving you headache

**Comment by franzliedke** [comment]
:+1:

**Pull request merged**
