### PR TITLE
Make PostStreamScrubber display numbers relating to only "comment" posts

### PR DESCRIPTION
**Pull request by ahsanity**
PR for #197.

This needs review as my expertise in JS / ES6 / JSX / Mithril is very limited. This is more an attempt to explore the frontend codebase. 

I would be glad to make improvements and changes if required.

### CODE REVIEW

**Comment by tobscure** [comment]
Thanks for taking this on!

Just tried it out – it's a good start but not quite there. The issue is that we only want to change the numbers that are displayed on the scrubber, without having an impact on the calculations of the scrubber's positioning. So instead of changing how the `count` is retrieved and skipping over non-`comment` items in the loop altogether, try:

* Changing the `.Scrubber-count` in the `view` to be the discussion's `commentsCount` instead of the stream's count
* Add a new instance variable (something like `commentsIndex`). In the `update` loop, check on the item data-type attributes and increment the `commentsIndex` for every comment post until the last visible one.
* Then render `commentsIndex` into `.Scrubber-index` in the `view` instead of `visibleIndex`, and also in `renderScrollbar`. This means we can also get rid of the `visibleIndex` method completely.

Does that make sense? Please let me know if you have any questions!

**Comment by ahsanity** [comment]
Yup, makes sense! I will take a bash at it later in the week. Thanks!

**Comment by ahsanity** [comment]
@tobscure have a look now. Thanks for such clear directions, you made it too easy ;)

**Comment by ahsanity** [comment]
Squashed my commits.

**Comment by Luceos** [comment]
@tobscure any feedback on this?

**Comment by tobscure** [comment]
Looks good, just need to test when I get a chance.

**Comment by tobscure** [comment]
Perfect, thanks!

**Comment by ahsanity** [comment]
Coolio!

**Pull request merged**
