### PR TITLE
Ask before mark all as read

### PR DESCRIPTION
**Pull request by sijad**
need to flarum/flarum-ext-english#61 be merged

### CODE REVIEW

**Comment by franzliedke** [comment]
I don't think we need a full-blown modal here. What do you think, @tobscure ?

**Comment by tobscure** [comment]
No I don't think it's necessary. A native confirmation is fine.

**Comment by sijad** [comment]
but native confirmation is ugly :cry:

**Comment by franzliedke** [comment]
> what about php file is that ok?
Don't worry about it, we're [getting rid of sudo mode](https://github.com/flarum/core/pull/735#issuecomment-170751644) in its current form anyway.

**Comment by sijad** [comment]
I'm closing this as i thought the modal is more efficient way to go, I know @bogdanteodoru is working on this too
@bogdanteodoru you can use the php file as the reference if you wanna :smile:

**Comment by franzliedke** [comment]
Okay, thanks for your initiative, though! :)

And also thanks for all the pull requests. Feels amazing.

**Comment by bogdanteodoru** [comment]
@sijad from what I know there won't be a modal requiring the password anymore so no need for PHP changes. But thanks for the heads up :+1:

**Comment by sijad** [comment]
@bogdanteodoru see https://github.com/flarum/core/issues/679#issuecomment-165262615 the check is still there, see [this](https://discuss.flarum.org/d/1835-development-setup) to install dev version

**Comment by bogdanteodoru** [comment]
@sijad see https://github.com/flarum/core/pull/735#issuecomment-170751644 @tobscure said we will remove that so no need to add it anymore. My initial commit included the PHP fix as well but removed it afterwards.

**Pull request closed without merging**
