### PR TITLE
Sorted

### PR DESCRIPTION
**Pull request by Justman10000**
Is that clearer

### CODE REVIEW

**Comment by davwheat** [comment]
We always keep our translations sorted alphabetically to make finding them easier. What's this attempting to fix? Could you provide a description?

**Comment by Justman10000** [comment]
> 
> 
> We always keep our translations sorted alphabetically to make finding them easier. What's this attempting to fix? Could you provide a description?

Oh well ... Well, it belongs together!

**Comment by SychO9** [comment]
They are together but alphabetically sorted.

**Review by tankerkiller125 — CHANGES_REQUESTED** [review]
We sort translations by alphabetical order. I don't think a change is required here.

**Comment by SychO9** [comment]
Thank you for the PR @Justman10000! but we alphabetically sort translation keys so this change is unnecessary. We do appreciate contributions however so don't be discouraged 👍🏼

**Pull request closed without merging**
